services:
  - type: web
    name: junkshop-pos
    env: python
    buildCommand: python render_build.py
    startCommand: python render_start.py
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: TIME_ZONE
        value: Asia/Manila
      - key: DATABASE_URL
        fromDatabase:
          name: junkshop-pos-db
          property: connectionString
      - key: DEFAULT_ADMIN_USERNAME
        sync: false
      - key: DEFAULT_ADMIN_PASSWORD
        sync: false
      - key: DEFAULT_ADMIN_EMAIL
        sync: false
      - key: GMAIL_ADDRESS
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false

databases:
  - name: junkshop-pos-db
    databaseName: junkshop_pos
    user: junkshop_pos
